name: flutter_chatbot
description: A Flutter ChatBot project powered by Dialogflow.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dialogflow: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/credentials.json
